language: scala
scala:
- 2.11.5
jdk:
- oraclejdk8
sudo: false
script:
- sbt ++$TRAVIS_SCALA_VERSION -J-XX:ReservedCodeCacheSize=256M clean coverage test
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
after_success:
- sbt coveralls
notifications:
  slack:
    secure: BQ/FjW3DTlKEQCtvWl2FjxtXPSkWBNEi8ZEjmJri1N9upa1HcWa+nctlIEsEmNHNXo2t8jup/knH+RMnaGG31sGwrwsWwtUXp6+NMzCyW8VzKnnotfARmBpkh4YVflfaHww15IwTfP8lzhsKJm/leposjFxgWOmdwgAeOK6G0mg=
